name: Manual action two

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Please use tag-like format n.n.n-someword (1.111.11-beta) beta
        required: true

jobs:
  trigger-circleci-release:
    runs-on: ubuntu-latest
    steps:

      - name: Trigger Release job
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Triggering Test release using BRANCH and TEST_TAG ${{ github.event.inputs.branch }}  ${{ github.ref }} "
